# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build And Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [14.4.0, 16.x, 18.x]
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: build gitbook
        run: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"
          npm i gitbook-cli
          cd node_modules/gitbook-cli
          npm i graceful-fs@4.1.4 --save
          cd node_modules/npm
          npm i graceful-fs@4.1.4 --save
          cd ../../../..
          node_modules/gitbook-cli/bin/gitbook.js install .
          node_modules/gitbook-cli/bin/gitbook.js build .
          echo "${{ steps.pages.outputs.host }}"
          echo "${{ steps.pages.outputs.host }}" > ./_book/CNAME
          
          echo 'node_modules/' > .gitignore
          echo 'npm-debug.log' >> .gitignore
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './_book'

  # deploy _book to branch gh-pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


